### PR TITLE
Add option to output build variables

### PR DESCRIPTION
**Pull request by martinvrba**

### CODE REVIEW

**Comment by martinvrba** [comment]
Fixed the commit author.

**Review by randombenj — APPROVED** [review]
LGTM, thanks for this awesome improvement!

**Comment by randombenj** [comment]
@neolynx could you review and merge?

**Comment by martinvrba** [comment]
Updated to use get_deploy_config(). Please re-review.

**Comment by martinvrba** [comment]
Changed BASEMIRROR to BASEVERSION.

**Pull request merged**
